import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/hero/Hero.component";
import HIW from "@/components/howItWork/HowItWork.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
      <meta charSet='UTF-8'/>
        <title>Bulk Write Guest Name on PDF Invitation Card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow"></meta>
        <meta name="author" content="Invitation.io"></meta>
      </Head>
      <Hero />
      <HIW />
    </>
  );
}
